# Generated by Django 5.0.1 on 2024-09-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AlterField(
            model_name='marketmanager',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
