# Generated by Django 5.0.1 on 2024-09-28 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketmanager',
            options={},
        ),
        migrations.AlterModelManagers(
            name='marketmanager',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='marketmanager',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='marketmanager',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='marketmanager',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='marketmanager',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='marketmanager',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='marketmanager',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='marketmanager',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='marketmanager',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='marketmanager',
            name='password',
        ),
        migrations.RemoveField(
            model_name='marketmanager',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='marketmanager',
            name='username',
        ),
        migrations.AddField(
            model_name='marketmanager',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
