# Generated by Django 5.0.1 on 2024-09-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_marketmanager_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketmanager',
            old_name='market_name',
            new_name='market_id',
        ),
    ]
