# Generated by Django 5.0.1 on 2024-09-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_market_name_marketmanager_market_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketmanager',
            name='username',
        ),
    ]
