# Generated by Django 5.0.1 on 2024-09-29 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0004_alter_market_manager'),
        ('users', '0009_remove_marketmanager_user_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketManager',
        ),
    ]
