# Generated by Django 5.0.1 on 2024-09-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='manager',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='market', to='users.marketmanager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='market_rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
