# Generated by Django 5.0.1 on 2024-09-25 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0002_market_manager_market_market_rules'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market', to='users.marketmanager'),
        ),
    ]
