# Generated by Django 5.0.1 on 2024-09-29 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0003_alter_market_manager'),
        ('users', '0009_remove_marketmanager_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market', to='users.userprofile'),
        ),
    ]
